---

- hosts: localhost
  gather_facts: False
  tasks:

    # [[IsOperationType::RunDockerContainer]]
    - name: execute_mediawiki_maintenance_runJobs
      shell: docker exec dataspectsstandardsystem_php-fpm_1 bash -c "php w/maintenance/runJobs.php && php w/extensions/SemanticMediaWiki/maintenance/rebuildData.php"
      tags:
        - execute_mediawiki_maintenance_runJobs
