---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: place_dataspects_search_config_files
      template:
        src: ../scripts/extract_dataspectsSystemCoreOntology_from_mediawiki.rb
        dest: "{{ dataspectsSystem_path_on_host }}/extract_dataspectsSystemCoreOntology_from_mediawiki.rb"
        mode: 0777
      tags:
        - extract_dataspectsSystemCoreOntology

    # [[IsOperationType::RunDockerContainer]]
    - name: Inject dataspectsSystemCoreOntology into mediawiki
      shell: docker run \
              --network dataspects_net \
              --ip {{ dataspects_net_ipam_subnet }}.12 \
              --volume {{ dataspectsSystem_path_on_host }}/:/usr/src/system_instance_root/ \
              --workdir /tmp/dataspects_lib \
              --rm \
                dataspects/dataspects:{{ dataspects_version }} \
                  bundle exec bin/dataspects \
                    --profile /usr/src/system_instance_root/standard_system_profiles.yml \
                      manage /usr/src/system_instance_root/extract_dataspectsSystemCoreOntology_from_mediawiki.rb
      ignore_errors: yes
      become: true
      tags:
        - DISABLED_extract_dataspectsSystemCoreOntology

# sudo docker run \
#   --network dataspects_net \
#   --ip 172.20.0.12 \
#   --volume /media/lex/LEXSAMSUNG-64GB/dataspectsSystem/docker_image_factory/dataspects/:/usr/src/docker_image_factory/dataspects/ \
#   --volume /home/lex/dataspectsStandardSystemkbook/:/usr/src/workspace/ \
#   --workdir /usr/src/docker_image_factory/dataspects/dataspects_lib \
#   --rm \
#     dataspects/dataspects:181029a \
#       bundle exec bin/dataspects \
#         --profile /usr/src/workspace/standard_system_profiles.yml \
#           manage /usr/src/workspace/inject_dataspectsSystemCoreOntology_into_mediawiki.rb
