---
- hosts: localhost
  gather_facts: False
  tasks:

    - name: Place elasticsearch index standard settings and mapping
      template:
        src: ../elasticsearch_standard_index_settings/{{ item }}
        dest: "{{ dataspectsSystem_path_on_host }}/{{ item }}"
        mode: 0777
      with_items:
        - elasticsearch_index_standard_mapping.rb
        - elasticsearch_index_standard_settings.rb
      tags:
        - reset_elasticsearch_index

    - name: Place reset_elasticsearch_index.rb
      template:
        src: ../scripts/reset_elasticsearch_index.rb
        dest: "{{ dataspectsSystem_path_on_host }}/reset_elasticsearch_index.rb"
        mode: 0777
      tags:
        - reset_elasticsearch_index

    - name: reset_elasticsearch_index
      shell: docker run \
              --network dataspects_net \
              --ip {{ dataspects_net_ipam_subnet }}.66 \
              --volume {{ dataspectsSystem_path_on_host }}/:/usr/src/system_instance_root/ \
              --workdir /tmp/dataspects_lib \
              --rm \
                dataspects/dataspects:{{ dataspects_version }} \
                  bundle exec bin/dataspects \
                    --profile /usr/src/system_instance_root/standard_system_profiles.yml \
                      manage /usr/src/system_instance_root/reset_elasticsearch_index.rb
      ignore_errors: yes
      become: true
      tags:
        - reset_elasticsearch_index
